# -*- coding: utf-8 -*-
{
    'name': 'Mantenimiento Moa Nickel',
    'description': """

    """,
    'version': '1.0',
    'category': '',
    'depends': ['maintenance', 'stock', 'l10n_cu_hr', 'l10n_cu_base', 'account_asset', 'stock_request_analytic', 'nl_cfg_reports'],
    'data': [
        'security/df_maintenance_security.xml',
        'security/ir.model.access.csv',
        'data/maintenance_sequence.xml',
        'data/maintenance_data.xml',
        'data/df_maintenance_account_data.xml',
        'data/df_maintenance_remove_settings.xml',
        'views/df_maintenance_request_views.xml',
        'views/df_maintenance_work_order_views.xml',
        'views/df_maintenance_equipment_views.xml',
        'views/df_maintenance_failure_cause_views.xml',
        'views/df_maintenance_plan_type_views.xml',
        'views/df_maintenance_intervention_views.xml',
        'views/df_maintenance_template_views.xml',
        'views/df_maintenance_rate_views.xml',
        'views/df_maintenance_activity_views.xml',
        'views/df_maintenance_stock_views.xml',
        'views/df_maintenance_teams_views.xml',
        'views/df_maintenance_brigade_views.xml',
        'views/df_maintenance_request_to_plant.xml',
        'views/df_maintenance_work_order_to_pant.xml',
        'views/df_configuration_department_centro_view.xml',
        'views/df_maintenance_physical_location_views.xml',
        'views/df_maintenance_equipment_category_views.xml',
        'views/df_maintenance_equipment_subcategory_views.xml',
        'views/df_maintenance_remove_settings_views.xml',
        'views/df_maintenance_request_area_views.xml',
        'views/df_maintenance_work_order_product_views.xml',
        'views/stock_request_view.xml',
        'views/df_maintenance_accounts_views.xml',
        'wizard/df_maintenance_work_order_assign_view.xml',
        'wizard/df_supervise_wizard_view.xml',
        'wizard/df_maintenance_work_order_cancel_view.xml',
        'wizard/df_maintenance_preventive_programming_view.xml',
        'wizard/df_maintenance_post_work_force_view.xml',
		'wizard/df_maintenance_request_cancel.xml',
		'wizard/df_message_view.xml',
		'wizard/df_maintenance_search_work_order.xml',
		'wizard/df_maintenance_transfer_between_orders_view.xml',
		'wizard/df_maintenance_check_exists.xml',
		'wizard/df_maintenance_expedition.xml',
        'wizard/df_maintenance_rpt_orders_wizard.xml',
        'wizard/df_maintenance_rpt_request_wizard.xml',
        'wizard/df_maintenance_rpt_orders_resumen_cost_mtto_wizard.xml',
        'wizard/df_maintenance_rpt_orders_resumen_cost_wizard.xml',
        'wizard/df_maintenance_rpt_maintenance_time_wizard.xml',
        'report/print_receipt_templates.xml',
        'report/df_maintenance_report.xml',
        'report/report_struc.xml',
        'report/report_view.xml',
        'report/print_orders_report.xml',
        'report/print_request_report.xml',
        'report/print_orders_resumen_cost_report.xml',
        'report/print_orders_resumen_cost_mtto_report.xml',
        'report/print_maintenance_time_report.xml',
        'report/print_maintenance_time_brigade_report.xml',

        'views/df_maintenance_menu_views.xml'
    ],

    'assets': {
        'web.assets_backend': [
            'df_maintenance/static/src/js/kanban_button.js',
        ],
        'web.assets_qweb': [
            'df_maintenance/static/src/xml/kanban_button.xml',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
